# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  phumelani.co.za:
    site_hosts:
      - canonical: phumelani.test
        redirects:
          - www.phumelani.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: ruargh@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
